language: php
php:
  - 7.1
services:
  - mongodb
cache:
  bundler: true
  directories:
    - www/vendor
install:
  - pecl install -f mongodb
  - cd www
  - composer install
  - cp tests/helpers/.env.test .env
script:
  - composer test