language: php
before_install:
  - sh -c "mkdir -p ${TRAVIS_BUILD_DIR}/travis/module-cache/`php-config --vernum`"
before_script:
  - MODULES="apcu.so:apcu-beta memcached.so:memcached mongodb.so:mongodb" ./travis/modulecache.sh
php:
  - 7.1
services:
  - mongodb
cache:
  bundler: true
  directories:
    - www/vendor
    - ${TRAVIS_BUILD_DIR}/travis/module-cache
install:
  - pecl install -f mongodb
  - cd www
  - composer install
  - cp tests/helpers/.env.test .env
script:
  - composer test